import {useEffect,useState} from 'react'; import {AlertTriangle,Camera,CheckCircle2,LogOut,RefreshCw,Shield,Train,Trash2} from 'lucide-react'; import {supabase} from './supabase';
const cleanDigits=(v,n)=>v.replace(/\D/g,'').slice(0,n);
export default function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setProfile(null);return} supabase.from('profiles').select('role,full_name').eq('id',session.user.id).single().then(({data,error})=>{if(error)setError(error.message);else setProfile(data)})},[session]);
 if(loading)return <Shell><div className="loader">Loading...</div></Shell>;
 if(!session)return <Login/>;
 if(!profile)return <Shell><div className="loader">Loading access level...</div>{error&&<Notice type="error">{error}</Notice>}</Shell>;
 return <Shell profile={profile} onLogout={()=>supabase.auth.signOut()}>{profile.role==='admin'?<Admin/>:<Report/>}</Shell>
}
function Shell({children,profile,onLogout}){return <><header><div className="brand"><span className="logo"><Train/></span><div><b>Train Defect Reporter</b><small>{profile?.role==='admin'?'Administrator dashboard':'Damage and vandalism reporting'}</small></div></div>{onLogout&&<button className="ghost" onClick={onLogout}><LogOut/> Sign out</button>}</header><main>{children}</main></>}
function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''); async function submit(e){e.preventDefault();setBusy(true);setError('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)} return <div className="login-wrap"><section className="login-card"><span className="logo big"><Train/></span><h1>Train Defect Reporter</h1><p>Secure staff login for reporting onboard damage and vandalism.</p><form onSubmit={submit}><label>Work email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<Notice type="error">{error}</Notice>}<button className="primary" disabled={busy}>{busy?'Signing in...':'Sign in'}</button></form></section></div>}
function Report(){const[form,setForm]=useState({train:'',coach:'',description:'',photo:null}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState(''); const valid=/^\d{6}$/.test(form.train)&&/^\d{3}$/.test(form.coach)&&form.description.trim().length>=5&&form.photo;
 async function submit(e){e.preventDefault();if(!valid)return;setBusy(true);setError('');setMsg(''); const uid=(await supabase.auth.getUser()).data.user.id; const ext=(form.photo.name.split('.').pop()||'jpg').toLowerCase(); const path=`${uid}/${crypto.randomUUID()}.${ext}`; let r=await supabase.storage.from('defect-images').upload(path,form.photo,{contentType:form.photo.type||'image/jpeg'}); if(r.error){setError(r.error.message);setBusy(false);return} r=await supabase.from('defects').insert({train_number:form.train,coach_number:form.coach,description:form.description.trim(),image_path:path,reported_by:uid}); if(r.error){await supabase.storage.from('defect-images').remove([path]);setError(r.error.message)}else{setMsg('Defect submitted successfully.');setForm({train:'',coach:'',description:'',photo:null});document.querySelector('#photo').value=''} setBusy(false)}
 return <section className="narrow"><div className="title"><h1>Report a defect</h1><p>Enter the details and attach a clear photo.</p></div>{msg&&<Notice type="success"><CheckCircle2/>{msg}</Notice>}{error&&<Notice type="error">{error}</Notice>}<form className="card form" onSubmit={submit}><label>Train number<input inputMode="numeric" placeholder="e.g. 801203" value={form.train} onChange={e=>setForm({...form,train:cleanDigits(e.target.value,6)})}/><small>6 digits</small></label><label>Coach number<input inputMode="numeric" placeholder="e.g. 822" value={form.coach} onChange={e=>setForm({...form,coach:cleanDigits(e.target.value,3)})}/><small>3 digits</small></label><label>Description<textarea rows="5" placeholder="Include the location, damage and any immediate risk" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="photo" htmlFor="photo"><Camera/><span>{form.photo?form.photo.name:'Take or choose a photo'}</span></label><input id="photo" className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>setForm({...form,photo:e.target.files?.[0]||null})}/><button className="primary" disabled={!valid||busy}>{busy?'Submitting...':'Submit defect'}</button></form></section>}
function Admin(){const[items,setItems]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''); async function load(){setBusy(true);const{data,error}=await supabase.from('defects').select('id,train_number,coach_number,description,image_path,created_at,profiles!defects_reported_by_fkey(full_name)').order('created_at',{ascending:false});if(error)setError(error.message);else{const enriched=await Promise.all((data||[]).map(async x=>{const{data:u}=await supabase.storage.from('defect-images').createSignedUrl(x.image_path,3600);return{...x,imageUrl:u?.signedUrl}}));setItems(enriched)}setBusy(false)} useEffect(()=>{load()},[]); async function remove(x){if(!confirm('Are you sure you want to delete this defect report? This cannot be undone.'))return;const{error}=await supabase.from('defects').delete().eq('id',x.id);if(error){setError(error.message);return}await supabase.storage.from('defect-images').remove([x.image_path]);setItems(items.filter(i=>i.id!==x.id))}
 return <section><div className="title row"><div><h1>Defect dashboard</h1><p>Review and manage all staff reports.</p></div><button className="ghost dark" onClick={load}><RefreshCw/> Refresh</button></div><div className="stats"><div className="card"><small>Total reports</small><strong>{items.length}</strong></div><div className="card"><small>Open reports</small><strong className="amber">{items.length}</strong></div><div className="card risk"><AlertTriangle/><span>Escalate urgent safety risks using your normal operational process.</span></div></div>{error&&<Notice type="error">{error}</Notice>}{busy?<div className="loader">Loading reports...</div>:items.length===0?<div className="card empty">No defects have been reported.</div>:<div className="reports">{items.map(x=><article className="card report" key={x.id}>{x.imageUrl?<img src={x.imageUrl} alt="Reported defect"/>:<div className="image-placeholder">No image</div>}<div className="report-body"><div className="chips"><span>Train {x.train_number}</span><span>Coach {x.coach_number}</span></div><h2>{x.description}</h2><p>{new Date(x.created_at).toLocaleString()} · {x.profiles?.full_name||'Staff user'}</p><button className="danger" onClick={()=>remove(x)}><Trash2/> Delete report</button></div></article>)}</div>}</section>}
function Notice({children,type}){return <div className={`notice ${type}`}>{children}</div>}
